// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmdzceMXvHxH750mT-Tnj7VHFkt4h7aqY',
    appId: '1:50058070959:web:cb4b9ec5989e07ffe03d5a',
    messagingSenderId: '50058070959',
    projectId: 'fyp-project-1ec07',
    authDomain: 'fyp-project-1ec07.firebaseapp.com',
    storageBucket: 'fyp-project-1ec07.firebasestorage.app',
    measurementId: 'G-CQ98DGTFB0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYSImznn29xd0S1ElY3792iZD_ozatix4',
    appId: '1:50058070959:android:c1a97b8e7636a9e1e03d5a',
    messagingSenderId: '50058070959',
    projectId: 'fyp-project-1ec07',
    storageBucket: 'fyp-project-1ec07.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnmVRQC1l63dTWd3myEzUT5wvKTJaUdYU',
    appId: '1:50058070959:ios:c2106d1fd7bdaf79e03d5a',
    messagingSenderId: '50058070959',
    projectId: 'fyp-project-1ec07',
    storageBucket: 'fyp-project-1ec07.firebasestorage.app',
    iosBundleId: 'com.example.fypProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnmVRQC1l63dTWd3myEzUT5wvKTJaUdYU',
    appId: '1:50058070959:ios:c2106d1fd7bdaf79e03d5a',
    messagingSenderId: '50058070959',
    projectId: 'fyp-project-1ec07',
    storageBucket: 'fyp-project-1ec07.firebasestorage.app',
    iosBundleId: 'com.example.fypProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmdzceMXvHxH750mT-Tnj7VHFkt4h7aqY',
    appId: '1:50058070959:web:8b357fe7dbdea6a2e03d5a',
    messagingSenderId: '50058070959',
    projectId: 'fyp-project-1ec07',
    authDomain: 'fyp-project-1ec07.firebaseapp.com',
    storageBucket: 'fyp-project-1ec07.firebasestorage.app',
    measurementId: 'G-0H9XH1Y67Z',
  );
}
