// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3FC_7zyKijoiFN2-CHBp0epL3mi7RHx8',
    appId: '1:271345142761:web:732cc30725426079865978',
    messagingSenderId: '271345142761',
    projectId: 'childsafetyesp32-4f526',
    authDomain: 'childsafetyesp32-4f526.firebaseapp.com',
    databaseURL: 'https://childsafetyesp32-4f526-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'childsafetyesp32-4f526.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByI-kdptS6Ow_CN8ztoodfwR4bsv9yVy0',
    appId: '1:271345142761:android:2b479350b6c639e2865978',
    messagingSenderId: '271345142761',
    projectId: 'childsafetyesp32-4f526',
    databaseURL: 'https://childsafetyesp32-4f526-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'childsafetyesp32-4f526.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbuJ08Wj4jNCBEuob_y9Ve5iwLn5ZSVrM',
    appId: '1:271345142761:ios:aa1a76178fb1363c865978',
    messagingSenderId: '271345142761',
    projectId: 'childsafetyesp32-4f526',
    databaseURL: 'https://childsafetyesp32-4f526-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'childsafetyesp32-4f526.firebasestorage.app',
    iosBundleId: 'com.example.fypProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbuJ08Wj4jNCBEuob_y9Ve5iwLn5ZSVrM',
    appId: '1:271345142761:ios:aa1a76178fb1363c865978',
    messagingSenderId: '271345142761',
    projectId: 'childsafetyesp32-4f526',
    databaseURL: 'https://childsafetyesp32-4f526-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'childsafetyesp32-4f526.firebasestorage.app',
    iosBundleId: 'com.example.fypProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3FC_7zyKijoiFN2-CHBp0epL3mi7RHx8',
    appId: '1:271345142761:web:823372c108c16bda865978',
    messagingSenderId: '271345142761',
    projectId: 'childsafetyesp32-4f526',
    authDomain: 'childsafetyesp32-4f526.firebaseapp.com',
    databaseURL: 'https://childsafetyesp32-4f526-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'childsafetyesp32-4f526.firebasestorage.app',
  );

}